```{r}
library(tidyverse)
library(dplyr)
```


```{r}
#calculate the yield curve
#we first calculate the dirty price by adding up the accrued interest and clean price
bonds <- read.csv("bonds_new.csv")
#bond_1 <- c(99.71,99.7,99.72,99.73,99.74,99.75,99.76,99.77,99.78,99.79)
bond_1 <- bonds[bonds$ISIN == 'CA135087H490',]
bond_2 <- bonds[bonds$ISIN == 'CA135087A610',]
bond_3 <- bonds[bonds$ISIN == 'CA135087J546',]
bond_4 <- bonds[bonds$ISIN == 'CA135087J967',]
bond_5 <- bonds[bonds$ISIN == 'CA135087K528',]
bond_6 <- bonds[bonds$ISIN == 'CA135087K940',]
bond_7 <- bonds[bonds$ISIN == 'CA135087L518',]
bond_8 <- bonds[bonds$ISIN == 'CA135087L930',]
bond_9 <- bonds[bonds$ISIN == 'CA135087M847',]
bond_10 <- bonds[bonds$ISIN == 'CA135087N837',]

coupon_rate_1 <- bond_1$coupon[1]/2
coupon_rate_2 <- bond_2$coupon[1]/2
coupon_rate_3 <- bond_3$coupon[1]/2
coupon_rate_4 <- bond_4$coupon[1]/2
coupon_rate_5 <- bond_5$coupon[1]/2
coupon_rate_6 <- bond_6$coupon[1]/2
coupon_rate_7 <- bond_7$coupon[1]/2
coupon_rate_8 <- bond_8$coupon[1]/2
coupon_rate_9 <- bond_9$coupon[1]/2
coupon_rate_10 <- bond_10$coupon[1]/2

Notional <-100

time_to_mature_1 <- as.numeric(as.Date(bond_1$maturity_data,"%m/%d/%Y")-as.Date(bond_1$date,"%m/%d/%Y"))/365
time_to_mature_2 <- as.numeric(as.Date(bond_2$maturity_data,"%m/%d/%Y")-as.Date(bond_2$date,"%m/%d/%Y"))/365
time_to_mature_3 <- as.numeric(as.Date(bond_3$maturity_data,"%m/%d/%Y")-as.Date(bond_3$date,"%m/%d/%Y"))/365
time_to_mature_4 <- as.numeric(as.Date(bond_4$maturity_data,"%m/%d/%Y")-as.Date(bond_4$date,"%m/%d/%Y"))/365
time_to_mature_5 <- as.numeric(as.Date(bond_5$maturity_data,"%m/%d/%Y")-as.Date(bond_5$date,"%m/%d/%Y"))/365
time_to_mature_6 <- as.numeric(as.Date(bond_6$maturity_data,"%m/%d/%Y")-as.Date(bond_6$date,"%m/%d/%Y"))/365
time_to_mature_7 <- as.numeric(as.Date(bond_7$maturity_data,"%m/%d/%Y")-as.Date(bond_7$date,"%m/%d/%Y"))/365
time_to_mature_8 <- as.numeric(as.Date(bond_8$maturity_data,"%m/%d/%Y")-as.Date(bond_8$date,"%m/%d/%Y"))/365
time_to_mature_9 <- as.numeric(as.Date(bond_9$maturity_data,"%m/%d/%Y")-as.Date(bond_9$date,"%m/%d/%Y"))/365
time_to_mature_10 <- as.numeric(as.Date(bond_10$maturity_data,"%m/%d/%Y")-as.Date(bond_10$date,"%m/%d/%Y"))/365



time_last_coupon_2 <- as.numeric(as.Date(bond_2$date,"%m/%d/%Y")-as.Date("2022-12-01"))/365
time_last_coupon_3 <- as.numeric(as.Date(bond_3$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_4 <- as.numeric(as.Date(bond_4$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_5 <- as.numeric(as.Date(bond_5$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_6 <- as.numeric(as.Date(bond_6$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_7 <- as.numeric(as.Date(bond_7$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_8 <- as.numeric(as.Date(bond_8$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_9 <- as.numeric(as.Date(bond_9$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365
time_last_coupon_10 <- as.numeric(as.Date(bond_10$date,"%m/%d/%Y")-as.Date("2022-9-01"))/365

#accrued interest
ac_2 <- time_last_coupon_2*coupon_rate_2
ac_3 <- time_last_coupon_3*coupon_rate_3
ac_4 <- time_last_coupon_4*coupon_rate_4
ac_5 <- time_last_coupon_5*coupon_rate_5
ac_6 <- time_last_coupon_6*coupon_rate_6
ac_7 <- time_last_coupon_7*coupon_rate_7
ac_8 <- time_last_coupon_8*coupon_rate_8
ac_9 <- time_last_coupon_9*coupon_rate_9
ac_10 <- time_last_coupon_10*coupon_rate_10

#dirty price
dirty_price_2 <- ac_2+bond_2$close_price
dirty_price_3 <- ac_3+bond_3$close_price
dirty_price_4 <- ac_4+bond_4$close_price
dirty_price_5 <- ac_5+bond_5$close_price
dirty_price_6 <- ac_6+bond_6$close_price
dirty_price_7 <- ac_7+bond_7$close_price
dirty_price_8 <- ac_8+bond_8$close_price
dirty_price_9 <- ac_9+bond_9$close_price
dirty_price_10 <- ac_10+bond_10$close_price
```




```{r}
#since the bond_1 matures within half a year, it is considered a zero coupon bond
spot_1 <- -log(bond_1$close_price/Notional)/time_to_mature_1 #ytm of the first bond

#bond_2 matures within half a year, it is considered a zero coupon bond
spot_2 <- -log(bond_2$close_price/Notional)/time_to_mature_2 #ytm of the first bond

#bond_3 matures between six months and one year
time_next_coupon <- as.numeric(as.Date("2023-3-01")-as.Date(bond_3$date,"%m/%d/%Y"))/365
p3_1 <- coupon_rate_3*Notional
p3_2 <- p3_1+Notional
r3_1 <- -log((p3_1)/Notional)/time_next_coupon
spot_3 <- -log((dirty_price_3-p3_1*exp(-r3_1*time_next_coupon))/p3_2)/(time_next_coupon+1/2)

#bond_4 has two coupon payments before mature
p4_c <- coupon_rate_4*Notional
p4_end <- p4_c+Notional
r4_1 <- -log((p4_c)/Notional)/time_next_coupon
seg4_1 <- p4_c*exp(-r4_1*time_next_coupon)

r4_2 <- -log((p4_c)/Notional)/(time_next_coupon+1/2)
seg4_2 <- p4_c*exp(-r4_2*(time_next_coupon+1/2))

spot_4 <- -log((dirty_price_4-seg4_1-seg4_2)/p4_end)/(time_next_coupon+1)

#bond_5 has 3 coupon payments before mature
p5_c <- coupon_rate_5*Notional
p5_end <- p5_c+Notional

r5_1 <- -log((p5_c)/Notional)/time_next_coupon
seg5_1 <- p5_c*exp(-r5_1*time_next_coupon)

r5_2 <- -log((p5_c)/Notional)/(time_next_coupon+1/2)
seg5_2 <- p5_c*exp(-r5_2*(time_next_coupon+1/2))

r5_3 <- -log((p5_c)/Notional)/(time_next_coupon+1)
seg5_3 <- p5_c*exp(-r5_3*(time_next_coupon+1))

spot_5 <- -log((dirty_price_5-seg5_1-seg5_2-seg5_3)/p5_end)/(time_next_coupon+3/2)

#bond_6 has 4 coupon payments before maturity
p6_c <- coupon_rate_6*Notional
p6_end <- p6_c+Notional

r6_1 <- -log((p6_c)/Notional)/time_next_coupon
seg6_1 <- p6_c*exp(-r6_1*time_next_coupon)

r6_2 <- -log((p6_c)/Notional)/(time_next_coupon+1/2)
seg6_2 <- p6_c*exp(-r6_2*(time_next_coupon+1/2))

r6_3 <- -log((p6_c)/Notional)/(time_next_coupon+1)
seg6_3 <- p6_c*exp(-r6_3*(time_next_coupon+1))

r6_4 <- -log((p6_c)/Notional)/(time_next_coupon+3/2)
seg6_4 <- p6_c*exp(-r6_4*(time_next_coupon+3/2))

spot_6 <- -log((dirty_price_6-seg6_1-seg6_2-seg6_3-seg6_4)/p6_end)/(time_next_coupon+2)

#bond_7 has 5 coupon payments before maturity
p7_c <- coupon_rate_7*Notional
p7_end <- p7_c+Notional

r7_1 <- -log((p7_c)/Notional)/time_next_coupon
seg7_1 <- p7_c*exp(-r7_1*time_next_coupon)

r7_2 <- -log((p7_c)/Notional)/(time_next_coupon+1/2)
seg7_2 <- p7_c*exp(-r7_2*(time_next_coupon+1/2))

r7_3 <- -log((p7_c)/Notional)/(time_next_coupon+1)
seg7_3 <- p7_c*exp(-r7_3*(time_next_coupon+1))

r7_4 <- -log((p7_c)/Notional)/(time_next_coupon+3/2)
seg7_4 <- p7_c*exp(-r7_4*(time_next_coupon+3/2))

r7_5 <- -log((p7_c)/Notional)/(time_next_coupon+2)
seg7_5 <- p7_c*exp(-r7_5*(time_next_coupon+2))

spot_7 <- -log((dirty_price_7-seg7_1-seg7_2-seg7_3-seg7_4-seg7_5)/p7_end)/(time_next_coupon+5/2)

#bond_8 has 6 coupon payments before maturity
p8_c <- coupon_rate_8*Notional
p8_end <- p8_c+Notional

r8_1 <- -log((p8_c)/Notional)/time_next_coupon
seg8_1 <- p8_c*exp(-r8_1*time_next_coupon)

r8_2 <- -log((p8_c)/Notional)/(time_next_coupon+1/2)
seg8_2 <- p8_c*exp(-r8_2*(time_next_coupon+1/2))

r8_3 <- -log((p8_c)/Notional)/(time_next_coupon+1)
seg8_3 <- p8_c*exp(-r8_3*(time_next_coupon+1))

r8_4 <- -log((p8_c)/Notional)/(time_next_coupon+3/2)
seg8_4 <- p8_c*exp(-r8_4*(time_next_coupon+3/2))

r8_5 <- -log((p8_c)/Notional)/(time_next_coupon+2)
seg8_5 <- p8_c*exp(-r8_5*(time_next_coupon+2))

r8_6 <- -log((p8_c)/Notional)/(time_next_coupon+5/2)
seg8_6 <- p8_c*exp(-r8_6*(time_next_coupon+5/2))

spot_8 <- -log((dirty_price_8-seg8_1-seg8_2-seg8_3-seg8_4-seg8_5-seg8_6)/p8_end)/(time_next_coupon+3)

#bond_9 has 7 coupon payments before maturity
p9_c <- coupon_rate_9*Notional
p9_end <- p9_c+Notional

r9_1 <- -log((p9_c)/Notional)/time_next_coupon
seg9_1 <- p9_c*exp(-r9_1*time_next_coupon)

r9_2 <- -log((p9_c)/Notional)/(time_next_coupon+1/2)
seg9_2 <- p9_c*exp(-r9_2*(time_next_coupon+1/2))

r9_3 <- -log((p9_c)/Notional)/(time_next_coupon+1)
seg9_3 <- p9_c*exp(-r9_3*(time_next_coupon+1))

r9_4 <- -log((p9_c)/Notional)/(time_next_coupon+3/2)
seg9_4 <- p9_c*exp(-r9_4*(time_next_coupon+3/2))

r9_5 <- -log((p9_c)/Notional)/(time_next_coupon+2)
seg9_5 <- p9_c*exp(-r9_5*(time_next_coupon+2))

r9_6 <- -log((p9_c)/Notional)/(time_next_coupon+5/2)
seg9_6 <- p9_c*exp(-r9_6*(time_next_coupon+5/2))

r9_7 <- -log((p9_c)/Notional)/(time_next_coupon+3)
seg9_7 <- p9_c*exp(-r9_7*(time_next_coupon+3))

spot_9 <- -log((dirty_price_9-seg9_1-seg9_2-seg9_3-seg9_4-seg9_5-seg9_6-seg9_7)/p9_end)/(time_next_coupon+7/2)

#bond_10 has 8 coupon payments before maturity
p10_c <- coupon_rate_10*Notional
p10_end <- p10_c+Notional

r10_1 <- -log((p10_c)/Notional)/time_next_coupon
seg10_1 <- p10_c*exp(-r10_1*time_next_coupon)

r10_2 <- -log((p10_c)/Notional)/(time_next_coupon+1/2)
seg10_2 <- p10_c*exp(-r10_2*(time_next_coupon+1/2))

r10_3 <- -log((p10_c)/Notional)/(time_next_coupon+1)
seg10_3 <- p10_c*exp(-r10_3*(time_next_coupon+1))

r10_4 <- -log((p10_c)/Notional)/(time_next_coupon+3/2)
seg10_4 <- p10_c*exp(-r10_4*(time_next_coupon+3/2))

r10_5 <- -log((p10_c)/Notional)/(time_next_coupon+2)
seg10_5 <- p10_c*exp(-r10_5*(time_next_coupon+2))

r10_6 <- -log((p10_c)/Notional)/(time_next_coupon+5/2)
seg10_6 <- p10_c*exp(-r10_6*(time_next_coupon+5/2))

r10_7 <- -log((p10_c)/Notional)/(time_next_coupon+3)
seg10_7 <- p10_c*exp(-r10_7*(time_next_coupon+3))

r10_8 <- -log((p10_c)/Notional)/(time_next_coupon+7/2)
seg10_8 <- p10_c*exp(-r10_8*(time_next_coupon+7/2))

spot_10 <- -log((dirty_price_10-seg10_1-seg10_2-seg10_3-seg10_4-seg10_5-seg10_6-seg10_7-seg10_8)/p10_end)/(time_next_coupon+4)


```

```{r}
#plot the ytm w.r.t. date 
spot_Jan_16 <- c(spot_1[1],spot_2[1],spot_3[1],spot_4[1],spot_5[1],spot_6[1],spot_7[1],spot_8[1],spot_9[1],spot_10[1])
spot_Jan_17 <- c(spot_1[2],spot_2[2],spot_3[2],spot_4[2],spot_5[2],spot_6[2],spot_7[2],spot_8[2],spot_9[2],spot_10[2])
spot_Jan_18 <- c(spot_1[3],spot_2[3],spot_3[3],spot_4[3],spot_5[3],spot_6[3],spot_7[3],spot_8[3],spot_9[3],spot_10[3])
spot_Jan_19 <- c(spot_1[4],spot_2[4],spot_3[4],spot_4[4],spot_5[4],spot_6[4],spot_7[4],spot_8[4],spot_9[4],spot_10[4])
spot_Jan_20 <- c(spot_1[5],spot_2[5],spot_3[5],spot_4[5],spot_5[5],spot_6[5],spot_7[5],spot_8[5],spot_9[5],spot_10[5])
spot_Jan_23 <- c(spot_1[6],spot_2[6],spot_3[6],spot_4[6],spot_5[6],spot_6[6],spot_7[6],spot_8[6],spot_9[6],spot_10[6])
spot_Jan_24 <- c(spot_1[7],spot_2[7],spot_3[7],spot_4[7],spot_5[7],spot_6[7],spot_7[7],spot_8[7],spot_9[7],spot_10[7])
spot_Jan_25 <- c(spot_1[8],spot_2[8],spot_3[8],spot_4[8],spot_5[8],spot_6[8],spot_7[8],spot_8[8],spot_9[8],spot_10[8])
spot_Jan_26 <- c(spot_1[9],spot_2[9],spot_3[9],spot_4[9],spot_5[9],spot_6[9],spot_7[9],spot_8[9],spot_9[9],spot_10[9])
spot_Jan_27 <- c(spot_1[10],spot_2[10],spot_3[10],spot_4[10],spot_5[10],spot_6[10],spot_7[10],spot_8[10],spot_9[10],spot_10[10])

time <- c(as.Date("2023-3-1"),as.Date("2023-6-1"),as.Date("2024-3-1"),as.Date("2024-9-1"),as.Date("2025-3-1"),as.Date("2025-9-1"),as.Date("2026-3-1"),as.Date("2026-9-1"),as.Date("2027-3-1"),as.Date("2027-9-1"))

plot(x=time,y=spot_Jan_16,type = "o",col="black",main="Spot Curve",xlab = "time",ylab = "spot rate")
lines(time, spot_Jan_17, type = "o",col="blue")
lines(time, spot_Jan_18, type = "o",col="red")
lines(time, spot_Jan_19, type = "o",col="green")
lines(time, spot_Jan_20, type = "o",col="yellow")
lines(time, spot_Jan_23, type = "o",col="brown")
lines(time, spot_Jan_24, type = "o",col="pink")
lines(time, spot_Jan_25, type = "o",col="purple")
lines(time, spot_Jan_26, type = "o",col="orange")
lines(time, spot_Jan_27, type = "o",col="azure")


legend("topright",c("Jan 16","Jan 17","Jan 18","Jan 19","Jan 20","Jan 23","Jan 24","Jan 25","Jan 26","Jan 27"),fill=c("black","blue","red","green","yellow","brown","pink","purple","orange","azure"))
```
```{r}
#yield to maturity rates
ytm_1 <- (Notional/bond_1$close_price)^(1/time_to_mature_1)-1
ytm_2 <- (Notional/bond_2$close_price)^(1/time_to_mature_2)-1

spot_seg3_1 <- (p3_1)/(1+spot_1)^(1/time_next_coupon)
ytm_3 <- (Notional/(dirty_price_3-spot_seg3_1))^(1/(time_next_coupon+1/2))-1

spot_seg4_1 <- (p4_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg4_2 <- (p4_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
ytm_4 <- (Notional/(dirty_price_4-spot_seg4_1-spot_seg4_2))^(1/(time_next_coupon+1))-1

spot_seg5_1 <- (p5_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg5_2 <- (p5_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
spot_seg5_3 <- (p5_c)/(1+spot_4)^(1/(time_next_coupon+1))
ytm_5 <- (Notional/(dirty_price_5-spot_seg5_1-spot_seg5_2-spot_seg5_3))^(1/(time_next_coupon+3/2))-1

spot_seg6_1 <- (p6_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg6_2 <- (p6_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
spot_seg6_3 <- (p6_c)/(1+spot_4)^(1/(time_next_coupon+1))
spot_seg6_4 <- (p6_c)/(1+spot_5)^(1/(time_next_coupon+3/2))
ytm_6 <- (Notional/(dirty_price_6-spot_seg6_1-spot_seg6_2-spot_seg6_3-spot_seg6_4))^(1/(time_next_coupon+2))-1

spot_seg7_1 <- (p7_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg7_2 <- (p7_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
spot_seg7_3 <- (p7_c)/(1+spot_4)^(1/(time_next_coupon+1))
spot_seg7_4 <- (p7_c)/(1+spot_5)^(1/(time_next_coupon+3/2))
spot_seg7_5 <- (p7_c)/(1+spot_6)^(1/(time_next_coupon+2))
ytm_7 <- (Notional/(dirty_price_7-spot_seg7_1-spot_seg7_2-spot_seg7_3-spot_seg7_4-spot_seg7_5))^(1/(time_next_coupon+5/2))-1

spot_seg8_1 <- (p8_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg8_2 <- (p8_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
spot_seg8_3 <- (p8_c)/(1+spot_4)^(1/(time_next_coupon+1))
spot_seg8_4 <- (p8_c)/(1+spot_5)^(1/(time_next_coupon+3/2))
spot_seg8_5 <- (p8_c)/(1+spot_6)^(1/(time_next_coupon+2))
spot_seg8_6 <- (p8_c)/(1+spot_7)^(1/(time_next_coupon+5/2))
ytm_8 <- (Notional/(dirty_price_8-spot_seg8_1-spot_seg8_2-spot_seg8_3-spot_seg8_4-spot_seg8_5))^(1/(time_next_coupon+3))-1

spot_seg9_1 <- (p9_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg9_2 <- (p9_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
spot_seg9_3 <- (p9_c)/(1+spot_4)^(1/(time_next_coupon+1))
spot_seg9_4 <- (p9_c)/(1+spot_5)^(1/(time_next_coupon+3/2))
spot_seg9_5 <- (p9_c)/(1+spot_6)^(1/(time_next_coupon+2))
spot_seg9_6 <- (p9_c)/(1+spot_7)^(1/(time_next_coupon+5/2))
spot_seg9_7 <- (p9_c)/(1+spot_8)^(1/(time_next_coupon+3))
ytm_9 <- (Notional/(dirty_price_9-spot_seg9_1-spot_seg9_2-spot_seg9_3-spot_seg9_4-spot_seg9_5))^(1/(time_next_coupon+7/2))-1

spot_seg10_1 <- (p10_c)/(1+spot_1)^(1/time_next_coupon)
spot_seg10_2 <- (p10_c)/(1+spot_3)^(1/(time_next_coupon+1/2))
spot_seg10_3 <- (p10_c)/(1+spot_4)^(1/(time_next_coupon+1))
spot_seg10_4 <- (p10_c)/(1+spot_5)^(1/(time_next_coupon+3/2))
spot_seg10_5 <- (p10_c)/(1+spot_6)^(1/(time_next_coupon+2))
spot_seg10_6 <- (p10_c)/(1+spot_7)^(1/(time_next_coupon+5/2))
spot_seg10_7 <- (p10_c)/(1+spot_8)^(1/(time_next_coupon+3))
spot_seg10_8 <- (p10_c)/(1+spot_9)^(1/(time_next_coupon+7/2))
ytm_10 <- (Notional/(dirty_price_10-spot_seg10_1-spot_seg10_2-spot_seg10_3-spot_seg10_4-spot_seg10_5))^(1/(time_next_coupon+4))-1
```

```{r}
#plot the spot curve w.r.t date

Jan_16 <- c(ytm_1[1],ytm_2[1],ytm_3[1],ytm_4[1],ytm_5[1],ytm_6[1],ytm_7[1],ytm_8[1],ytm_9[1],ytm_10[1])
Jan_17 <- c(ytm_1[2],ytm_2[2],ytm_3[2],ytm_4[2],ytm_5[2],ytm_6[2],ytm_7[2],ytm_8[2],ytm_9[2],ytm_10[2])
Jan_18 <- c(ytm_1[3],ytm_2[3],ytm_3[3],ytm_4[3],ytm_5[3],ytm_6[3],ytm_7[3],ytm_8[3],ytm_9[3],ytm_10[3])
Jan_19 <- c(ytm_1[4],ytm_2[4],ytm_3[4],ytm_4[4],ytm_5[4],ytm_6[4],ytm_7[4],ytm_8[4],ytm_9[4],ytm_10[4])
Jan_20 <- c(ytm_1[5],ytm_2[5],ytm_3[5],ytm_4[5],ytm_5[5],ytm_6[5],ytm_7[5],ytm_8[5],ytm_9[5],ytm_10[5])
Jan_23 <- c(ytm_1[6],ytm_2[6],ytm_3[6],ytm_4[6],ytm_5[6],ytm_6[6],ytm_7[6],ytm_8[6],ytm_9[6],ytm_10[6])
Jan_24 <- c(ytm_1[7],ytm_2[7],ytm_3[7],ytm_4[7],ytm_5[7],ytm_6[7],ytm_7[7],ytm_8[7],ytm_9[7],ytm_10[7])
Jan_25 <- c(ytm_1[8],ytm_2[8],ytm_3[8],ytm_4[8],ytm_5[8],ytm_6[8],ytm_7[8],ytm_8[8],ytm_9[8],ytm_10[8])
Jan_26 <- c(ytm_1[9],ytm_2[9],ytm_3[9],ytm_4[9],ytm_5[9],ytm_6[9],ytm_7[9],ytm_8[9],ytm_9[9],ytm_10[9])
Jan_27 <- c(ytm_1[10],ytm_2[10],ytm_3[10],ytm_4[10],ytm_5[10],ytm_6[10],ytm_7[10],ytm_8[10],ytm_9[10],ytm_10[10])

plot(x=time,y=Jan_16,type = "o",col="black",main="Yield-to-maturity Curve",xlab = "time",ylab = "ytm")

lines(time, Jan_17, type = "o",col="blue")
lines(time, Jan_18, type = "o",col="red")
lines(time, Jan_19, type = "o",col="green")
lines(time, Jan_20, type = "o",col="yellow")
lines(time, Jan_23, type = "o",col="brown")
lines(time, Jan_24, type = "o",col="pink")
lines(time, Jan_25, type = "o",col="purple")
lines(time, Jan_26, type = "o",col="orange")
lines(time, Jan_27, type = "o",col="azure")
legend("topright",c("Jan 16","Jan 17","Jan 18","Jan 19","Jan 20","Jan 23","Jan 24","Jan 25","Jan 26","Jan 27"),fill=c("black","blue","red","green","yellow","brown","pink","purple","orange","azure"))
```

```{r}
for_rate_1 <- (-spot_1*time_to_mature_1+spot_3*(time_to_mature_1+1))/1
for_rate_2 <- (-spot_1*time_to_mature_1+spot_4*(time_to_mature_1+3/2))/(3/2)
for_rate_3 <- (-spot_1*time_to_mature_1+spot_5*(time_to_mature_1+2))/2
for_rate_4 <- (-spot_1*time_to_mature_1+spot_6*(time_to_mature_1+5/2))/(5/2)
for_rate_5 <- (-spot_1*time_to_mature_1+spot_7*(time_to_mature_1+3))/3
for_rate_6 <- (-spot_1*time_to_mature_1+spot_8*(time_to_mature_1+7/2))/(7/2)
for_rate_7 <- (-spot_1*time_to_mature_1+spot_9*(time_to_mature_1+4))/4
for_rate_8 <- (-spot_1*time_to_mature_1+spot_10*(time_to_mature_1+9/2))/(9/2)

forr_Jan_16 <- c(for_rate_1[1],for_rate_2[1],for_rate_3[1],for_rate_4[1],for_rate_5[1],for_rate_6[1],for_rate_7[1],for_rate_8[1])
forr_Jan_17 <- c(for_rate_1[2],for_rate_2[2],for_rate_3[2],for_rate_4[2],for_rate_5[2],for_rate_6[2],for_rate_7[2],for_rate_8[2])
forr_Jan_18 <- c(for_rate_1[3],for_rate_2[3],for_rate_3[3],for_rate_4[3],for_rate_5[3],for_rate_6[3],for_rate_7[3],for_rate_8[3])
forr_Jan_19 <- c(for_rate_1[4],for_rate_2[4],for_rate_3[4],for_rate_4[4],for_rate_5[4],for_rate_6[4],for_rate_7[4],for_rate_8[4])
forr_Jan_20 <- c(for_rate_1[5],for_rate_2[5],for_rate_3[5],for_rate_4[5],for_rate_5[5],for_rate_6[5],for_rate_7[5],for_rate_8[5])
forr_Jan_23 <- c(for_rate_1[6],for_rate_2[6],for_rate_3[6],for_rate_4[6],for_rate_5[6],for_rate_6[6],for_rate_7[6],for_rate_8[6])
forr_Jan_24 <- c(for_rate_1[7],for_rate_2[7],for_rate_3[7],for_rate_4[7],for_rate_5[7],for_rate_6[7],for_rate_7[7],for_rate_8[7])
forr_Jan_25 <- c(for_rate_1[8],for_rate_2[8],for_rate_3[8],for_rate_4[8],for_rate_5[8],for_rate_6[8],for_rate_7[8],for_rate_8[8])
forr_Jan_26 <- c(for_rate_1[9],for_rate_2[9],for_rate_3[9],for_rate_4[9],for_rate_5[9],for_rate_6[9],for_rate_7[9],for_rate_8[9])
forr_Jan_27 <- c(for_rate_1[10],for_rate_2[10],for_rate_3[10],for_rate_4[10],for_rate_5[10],for_rate_6[10],for_rate_7[10],for_rate_8[10])

plot(x=forward_time,y=forr_Jan_16,type = "o",col="black",main="Forward Curve",xlab = "time difference",ylab = "forward rate")
lines(forward_time, forr_Jan_17, type = "o",col="blue")
lines(forward_time, forr_Jan_18, type = "o",col="red")
lines(forward_time, forr_Jan_19, type = "o",col="green")
lines(forward_time, forr_Jan_20, type = "o",col="yellow")
lines(forward_time, forr_Jan_23, type = "o",col="brown")
lines(forward_time, forr_Jan_24, type = "o",col="pink")
lines(forward_time, forr_Jan_25, type = "o",col="purple")
lines(forward_time, forr_Jan_26, type = "o",col="orange")
lines(forward_time, forr_Jan_27, type = "o",col="azure")

legend("topright",c("Jan 16","Jan 17","Jan 18","Jan 19","Jan 20","Jan 23","Jan 24","Jan 25","Jan 26","Jan 27"),fill=c("black","blue","red","green","yellow","brown","pink","purple","orange","azure"))

```
```{r}
X_1 <-log(ytm_1[-c(1)]/ytm_1[-c(10)])
X_2 <-log(ytm_2[-c(1)]/ytm_1[-c(10)])
X_3 <-log(ytm_3[-c(1)]/ytm_1[-c(10)])
X_4 <-log(ytm_4[-c(1)]/ytm_1[-c(10)])
X_5 <-log(ytm_5[-c(1)]/ytm_1[-c(10)])
X <- cbind(X_1,X_2,X_3,X_4,X_5)
Cov_X <- cov(X)
Cov_X

Y_1 <- -log(for_rate_1[-c(1)]/for_rate_1[-c(10)])
Y_2 <- -log(for_rate_2[-c(1)]/for_rate_2[-c(10)])
Y_3 <- -log(for_rate_3[-c(1)]/for_rate_3[-c(10)])
Y_4 <- -log(for_rate_4[-c(1)]/for_rate_4[-c(10)])
Y_5 <- -log(for_rate_5[-c(1)]/for_rate_5[-c(10)])
Y <- cbind(Y_1,Y_2,Y_3,Y_4,Y_5)
Cov_Y <- cov(Y)
Cov_Y
```

```{r}
ev_X <- eigen(Cov_X)
ev_X$values
ev_X$vectors
ev_Y <- eigen(Cov_Y)
ev_Y$values
ev_Y$vectors
```

